# Generated by Django migration system

from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_commentthread_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commentthread',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Indicates if this thread has been soft deleted'),
        ),
        migrations.AddField(
            model_name='commentthread',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, help_text='Timestamp when this thread was soft deleted'),
        ),
        migrations.AddField(
            model_name='commentthread',
            name='deleted_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET_NULL,
                related_name='commentthread_deleted',
                to=settings.AUTH_USER_MODEL,
                help_text='User who soft deleted this thread'
            ),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Indicates if this comment has been soft deleted'),
        ),
        migrations.AddField(
            model_name='comment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, help_text='Timestamp when this comment was soft deleted'),
        ),
        migrations.AddField(
            model_name='comment',
            name='deleted_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET_NULL,
                related_name='comment_deleted',
                to=settings.AUTH_USER_MODEL,
                help_text='User who soft deleted this comment'
            ),
        ),
    ]