# Generated by Django 5.2.7 on 2025-12-11 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0005_moderationauditlog_comment_is_spam_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, help_text="When this content was soft deleted", null=True
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who soft deleted this content",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_%(class)s",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="is_deleted",
            field=models.BooleanField(
                default=False, help_text="Whether this content has been soft deleted"
            ),
        ),
        migrations.AddField(
            model_name="commentthread",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, help_text="When this content was soft deleted", null=True
            ),
        ),
        migrations.AddField(
            model_name="commentthread",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who soft deleted this content",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_%(class)s",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="commentthread",
            name="is_deleted",
            field=models.BooleanField(
                default=False, help_text="Whether this content has been soft deleted"
            ),
        ),
        migrations.AddField(
            model_name="coursestat",
            name="deleted_replies",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="coursestat",
            name="deleted_responses",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="coursestat",
            name="deleted_threads",
            field=models.IntegerField(default=0),
        ),
    ]
