# Generated by Django 5.2.10 on 2026-02-12 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0006_comment_deleted_at_comment_deleted_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscussionMuteException",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course_id",
                    models.CharField(
                        db_index=True,
                        help_text="Course where the exception applies",
                        max_length=255,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "forum_discussion_mute_exception",
            },
        ),
        migrations.CreateModel(
            name="DiscussionMuteRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course_id",
                    models.CharField(
                        db_index=True,
                        help_text="Course in which mute applies",
                        max_length=255,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[("personal", "Personal"), ("course", "Course-wide")],
                        db_index=True,
                        default="personal",
                        help_text="Scope of the mute (personal or course-wide)",
                        max_length=10,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, help_text="Optional reason for muting"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether the mute is currently active"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("muted_at", models.DateTimeField(auto_now_add=True)),
                ("unmuted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "forum_discussion_user_mute",
            },
        ),
        migrations.AddField(
            model_name="moderationauditlog",
            name="course_id",
            field=models.CharField(
                blank=True,
                help_text="Course where the moderation action was performed",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="moderationauditlog",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Additional metadata for mute moderation",
            ),
        ),
        migrations.AddField(
            model_name="moderationauditlog",
            name="reason",
            field=models.TextField(
                blank=True, help_text="Optional reason for mute/unmute action"
            ),
        ),
        migrations.AddField(
            model_name="moderationauditlog",
            name="scope",
            field=models.CharField(
                blank=True,
                help_text="Scope of mute action (personal or course)",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="moderationauditlog",
            index=models.Index(
                fields=["course_id"], name="forum_moder_course__a3357b_idx"
            ),
        ),
        migrations.AddField(
            model_name="discussionmuteexception",
            name="exception_user",
            field=models.ForeignKey(
                help_text="User who unmuted the muted_user for themselves",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forum_mute_exceptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="discussionmuteexception",
            name="muted_user",
            field=models.ForeignKey(
                help_text="User who is globally muted in this course",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forum_mute_exceptions_for",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="discussionmuterecord",
            name="muted_by",
            field=models.ForeignKey(
                help_text="User performing the mute",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forum_muted_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="discussionmuterecord",
            name="muted_user",
            field=models.ForeignKey(
                help_text="User being muted",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forum_muted_by_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="discussionmuterecord",
            name="unmuted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who performed the unmute action",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="forum_mute_unactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="discussionmuteexception",
            index=models.Index(
                fields=["muted_user", "course_id"],
                name="forum_discu_muted_u_0c7d93_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="discussionmuteexception",
            index=models.Index(
                fields=["exception_user", "course_id"],
                name="forum_discu_excepti_cc37bb_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="discussionmuteexception",
            unique_together={("muted_user", "exception_user", "course_id")},
        ),
        migrations.AddIndex(
            model_name="discussionmuterecord",
            index=models.Index(
                fields=["muted_user", "course_id", "is_active"],
                name="forum_discu_muted_u_2d9bf1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="discussionmuterecord",
            index=models.Index(
                fields=["muted_by", "course_id", "scope"],
                name="forum_discu_muted_b_18ad23_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="discussionmuterecord",
            index=models.Index(
                fields=["scope", "course_id", "is_active"],
                name="forum_discu_scope_da97a8_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="discussionmuterecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("scope", "personal")),
                fields=("muted_user", "muted_by", "course_id", "scope"),
                name="forum_unique_active_personal_mute",
            ),
        ),
        migrations.AddConstraint(
            model_name="discussionmuterecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("scope", "course")),
                fields=("muted_user", "course_id"),
                name="forum_unique_active_course_mute",
            ),
        ),
    ]
