# Generated by Django 5.2.9 on 2025-12-23 09:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_add_discussion_ban_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='moderationauditlog',
            name='forum_moder_origina_c51089_idx',
        ),
        migrations.RemoveIndex(
            model_name='moderationauditlog',
            name='forum_moder_moderat_c62a1c_idx',
        ),
        migrations.AddField(
            model_name='moderationauditlog',
            name='action_type',
            field=models.CharField(choices=[('ban_user', 'Ban User'), ('ban_reactivate', 'Ban Reactivated'), ('unban_user', 'Unban User'), ('ban_exception', 'Ban Exception Created'), ('bulk_delete', 'Bulk Delete'), ('flagged', 'Content Flagged'), ('soft_deleted', 'Content Soft Deleted'), ('approved', 'Content Approved'), ('no_action', 'No Action Taken')], db_index=True, default='no_action', help_text='Type of moderation action taken', max_length=50),
        ),
        migrations.AddField(
            model_name='moderationauditlog',
            name='course_id',
            field=models.CharField(blank=True, db_index=True, help_text='Course ID for course-level moderation actions', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moderationauditlog',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Additional context (task IDs, counts, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='moderationauditlog',
            name='reason',
            field=models.TextField(blank=True, help_text='Reason provided for the moderation action', null=True),
        ),
        migrations.AddField(
            model_name='moderationauditlog',
            name='scope',
            field=models.CharField(blank=True, help_text='Scope of moderation (course/organization)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='moderationauditlog',
            name='target_user',
            field=models.ForeignKey(blank=True, help_text='Target user for user moderation actions (ban/unban)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_log_actions_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='discussionmoderationlog',
            name='action_type',
            field=models.CharField(choices=[('ban_user', 'Ban User'), ('unban_user', 'Unban User'), ('ban_reactivate', 'Ban Reactivated'), ('ban_exception', 'Ban Exception Created'), ('bulk_delete', 'Bulk Delete')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='moderationauditlog',
            name='actions_taken',
            field=models.JSONField(blank=True, help_text="List of actions taken (for AI: ['flagged', 'soft_deleted'])", null=True),
        ),
        migrations.AlterField(
            model_name='moderationauditlog',
            name='body',
            field=models.TextField(blank=True, help_text='Content body that was moderated (for content moderation)', null=True),
        ),
        migrations.AlterField(
            model_name='moderationauditlog',
            name='classification',
            field=models.CharField(blank=True, choices=[('spam', 'Spam'), ('spam_or_scam', 'Spam or Scam')], help_text='AI classification result', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='moderationauditlog',
            name='classifier_output',
            field=models.JSONField(blank=True, help_text='Full output from the AI classifier', null=True),
        ),
        migrations.AlterField(
            model_name='moderationauditlog',
            name='moderator',
            field=models.ForeignKey(blank=True, help_text='Human moderator who performed or overrode the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_log_actions_performed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='moderationauditlog',
            name='original_author',
            field=models.ForeignKey(blank=True, help_text='Original author of the moderated content', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderated_content', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='moderationauditlog',
            name='reasoning',
            field=models.TextField(blank=True, help_text='AI reasoning for the decision', null=True),
        ),
        migrations.AlterField(
            model_name='moderationauditlog',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When the moderation action was taken'),
        ),
        migrations.AddIndex(
            model_name='moderationauditlog',
            index=models.Index(fields=['action_type', '-timestamp'], name='forum_moder_action__32bd31_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationauditlog',
            index=models.Index(fields=['source', '-timestamp'], name='forum_moder_source_cf1224_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationauditlog',
            index=models.Index(fields=['target_user', '-timestamp'], name='forum_moder_target__cadf75_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationauditlog',
            index=models.Index(fields=['original_author', '-timestamp'], name='forum_moder_origina_6bb4d3_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationauditlog',
            index=models.Index(fields=['moderator', '-timestamp'], name='forum_moder_moderat_2c467c_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationauditlog',
            index=models.Index(fields=['course_id', '-timestamp'], name='forum_moder_course__9cbd6e_idx'),
        ),
    ]
